### ISSUE TITLE
Problem with running the Federated trust across Service Mesh domains example.

### ISSUE THREAD

**Issue by leoGHUBB** [trevorbox/service-mesh-patterns#19]
Running:
```
$helm upgrade -i istio-system-control-plane -n istio-system helm/istio-system-control-plane
```
gives the following error:
```
Release "istio-system-control-plane" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ServiceMeshControlPlane" in version "maistra.io/v1", unable to recognize "": no matches for kind "ServiceMeshMember" in version "maistra.io/v1"]
```
Running:
```
helm upgrade -i istio-system2-control-plane -n istio-system2 helm/istio-system2-control-plane
```
gives the same kind of error:
```
Release "istio-system2-control-plane" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ServiceMeshControlPlane" in version "maistra.io/v1", unable to recognize "": no matches for kind "ServiceMeshMember" in version "maistra.io/v1"]
```

**Comment by trevorbox** [comment]
Ah ok, the instructions assumed the operators were already installed. I added a step for installing them. Thanks!
https://github.com/trevorbox/service-mesh-patterns/tree/master/multi-cluster-trust#deploy-the-service-mesh-operators-if-not-already-installed

**Comment by leoGHUBB** [comment]
Thank you for looking into and fixing that.
I also have to modify:
```
export IP_ADDRESSES=$(echo "{$(echo $(host $(oc get route mongo -n istio-system2 -o jsonpath={'.spec.host'}) | cut -d" " -f4) | sed -e "s/ /,/g")}")
```
to:
```
export IP_ADDRESSES=$(echo "{$(echo $(host $(oc get route mongo -n istio-system2 -o jsonpath={'.spec.host'}) | cut -d" " -f4 | sed -e "s/alias//g" | tr -d '\n'))}")
```
to get the sample going.

However, I am still not able to reproduce the final outcome of getting the single star rating to validate that mTLS worked between the SMCP domains after following all the steps diligently.  Any further idea as to what could go wrong?

One thing thing I notice in the OSSM v2.x release notes from:
[https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/installing-ossm.html](url)
is that the namespace for elasticsearch operator should be openshift-operators-redhat and not openshift-operators which is different from your example which was set to openshift-operators.  Not even sure if that have any bearing to the failure of the results I am seeing.

I am using OCP 4.5 instead of 4.6 and have modified the values.yaml file in  multi-cluster-trust/helm/operators accordingly.

**Comment by leoGHUBB** [comment]
Interesting the sidecar for mongodb does not get created.
